### ISSUE TITLE
Neat but I need more info

### ISSUE THREAD

**Issue by ghostsquad** [JethroLogger/Jethro#3]
This looks neat, but I need more information. This seems like it might compete with Log4JS.
https://github.com/nomiddlename/log4js-node

Can you tell me how to:
* register appenders
* log to a file
* log specific minimum severity

**Comment by Hunchmun** [comment]
Hi, I'm really glad you find this useful!

Jethro is by no means feature complete yet, but at least it is stable. We currently do not have support for appenders, in the sense I believe you are enquiring for. 

To log to a file, this is currently not possible in Jethro v2, but is possible in Jethro v1, you can check the documentation on how to do that also included in this repo, but I feel like you will find the configuration mechanisms to be clumsy at best. Alternatively, I would use this:

```js
var logger = require('jethro');
logger.on("logger", function(data){
    logger.output(data, function(a){
        //Log to File variable: a
    });
});```

For logging specific severities, this was implemented in v1, but taken out... v1 was not as stable as v2 and I haven't had time to reimplement all of the old features, my apologies. You might find success in again, listening to the logger events, and formatting them appropriately. 

If you do that, use `logger.setConsole(false)` to force console output to be off, and then rely on your own custom handler, to select which logs you'd like to log and how you'd like to handle logic for logging things.

You can find additional documentation here: https://github.com/JethroLogger/Jethro/tree/master/docs/v2

Thanks again for using Jethro, please don't hesitate to ask if you have any more questions!

**Comment by ghostsquad** [comment]
This looks good enough as a simple drop-in console logger replacement, but I will most likely use Log4JS for any other needs I have. Thanks!

**Comment by ghostsquad** [comment]
Do you have plans to add enough functionality to this to compete with Log4JS?
