### ISSUE TITLE
Extending the Jethro class

### ISSUE THREAD

**Issue by MrJohnCoder** [JethroLogger/Jethro#7]
Due to how Jethro exports functions, and not itself, it is (as far as I can tell), impossible to extend it. Could this be changed, if needed I'll even submit a PR myself. Thanks

**Comment by Hunchmun** [comment]
Hi John,

Thanks for your interest in Jethro,

I've added `module.exports.Constructor = Jethro` if that hopefully solves your use case?

I'm also playing around with the idea of breaking Jethro up a little bit to be more modularised with fewer proxy functions for the plugin and transport features. Unfortunately, the export of the functions was to maintain backward compatibility with previous versions of the code (And to allow easy use without initialization). 

If this isn't sufficient please do feel free to submit a PR enabling your intended functionality,

Thanks

**Comment by MrJohnCoder** [comment]
Alright, thanks for doing that. I had a little too much time and rewrote the entire thing as classes  [here](https://github.com/FlexLabs/Jethro) .

**Comment by Hunchmun** [comment]
I'm going to try and find some bandwidth to expand upon this, @MrJohnCoder do you have any feature requests/API changes if you've been using this for any duration?

**Comment by MrJohnCoder** [comment]
Not really, the ability to extend the Jethro class was my main nitpick and that's already been solved. Other than that, my experience has been smooth sailing!

**Comment by Hunchmun** [comment]
Thanks a lot for your support @MrJohnCoder ! Going to mark this issue as closed now that I've updated the vulnerable dependencies! :)
